# Generated by Django 4.0 on 2021-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Date')),
                ('local_id', models.IntegerField()),
                ('local_nombre', models.CharField(max_length=400, verbose_name='Local Nombre')),
                ('comuna_nombre', models.CharField(max_length=400, verbose_name='Local Nombre')),
                ('fk_localidad', models.IntegerField()),
                ('localidad_nombre', models.CharField(max_length=400, verbose_name='Localidad Nombre')),
                ('local_direccion', models.CharField(max_length=400, verbose_name='Local Direccion')),
                ('funcionamiento_hora_apertura', models.TimeField()),
                ('funcionamiento_hora_cierre', models.TimeField(verbose_name='')),
                ('local_telefono', models.CharField(max_length=20, verbose_name='Local Telefono')),
                ('local_lat', models.CharField(max_length=100, verbose_name='Local Latitud')),
                ('local_lng', models.CharField(max_length=100, verbose_name='Local Longitud')),
                ('functionamiento_dia', models.CharField(max_length=50, verbose_name='Local Nombre')),
                ('fk_region', models.IntegerField()),
                ('fk_comuna', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
